pipeline {
    agent any
    environment {
        PATH ="C:\\Windows\\System32"
        
    }

    stages {
        stage('RemoveDirectory') {
            steps {
                echo 'Hello World'
                // bat 'rmdir /s /q abc'
            }
        }
        stage('CreateDirectory') {
            steps {
                echo 'Hello World'
                bat 'mkdir abc'
            }
        }
    }
}
